# https://github.com/volantis-x/hexo-theme-volantis/blob/dev/_config.yml

############################### Navigation Bar ############################### > start
navbar:
  visiable: auto # always, auto
  logo: # choose [img] or [icon + title]
    img: '' # volantis-static/media/org.volantis/blog/Logo-NavBar@3x.png
    icon:
    title: '千反田 <sup style="color:#ff9800">Blog</sup>'
  search: Search... # Search bar placeholder
  menu:
    - name: 首页
      icon: fa-duotone fa-feather-pointed teal
      url: /
      target: _self

    - name: 导航
      icon: fa-duotone fa-fan fa-spin PETERRIVE
      url: https://sukiu.top
      rows:
        - name: 分类
          icon: fa-duotone fa-folder-open SUNFLOWER
          url: /categories/
        - name: 标签
          icon: fa-duotone fa-tags GREENSEA
          url: /tags/
        - name: 归档
          icon: fa-duotone fa-box-archive PETERRIVE
          url: /archives/

    - name: 切换
      icon: fa-duotone fa-moon CARROT
      toggle: darkmode

    - name: 关于
      icon: fa-duotone fa-circle-info ORANGE
      url: /about/

    - name: 开往
      icon: fa-duotone fa-train-subway NEPHRITIS
      url: https://www.travellings.cn/go.html
############################### Navigation Bar ############################### > end

############################### Cover ######################################## > start
cover:
  height_scheme: full # full, half
  layout_scheme: search # blank (留白), search (搜索), dock (坞), featured (精选), focus (焦点)
  background: https://cdn.jsdelivr.net/gh/SukiEva/HexoBlog/source/static/images/background.webp
  display:
    home: true
    archive: true
    others: true # can be written in front-matter 'cover: true'
  title: 'SukiEva'
  subtitle: ''
  search: わたし、気になります！ # search bar placeholder
  features:
    - name: 首页
      url: /
    - name: 归档
      url: /archives/
    - name: 分类
      url: /categories/
    - name: 标签
      url: /tags/
    - name: 关于
      url: /about/
############################### Cover ######################################## > end

############################### Article Layout ############################### > start
# 文章
article:
  # 文章列表页面的文章卡片布局方案
  preview:
    scheme: landscape # landscape
    # pin icon for post
    pin_icon: https://cdn.jsdelivr.net/gh/twitter/twemoji@13.0/assets/svg/1f4cc.svg
    # auto generate title if not exist
    auto_title: false # false, true
    # auto generate excerpt if not exist
    auto_excerpt: false # false, true
    # hide excerpt
    hide_excerpt: false
    # show split line or not
    line_style: hidden # hidden, solid, dashed, dotted
    # show author
    author: false
    # show readmore button
    readmore: auto # auto, always
  # 文章详情页面的文章卡片本体布局方案
  body:
    # 文章顶部信息 从 meta_library 中取
    top_meta: [date, updated, wordcount, counter]
    # 文章底部信息 从 meta_library 中取
    bottom_meta: [category, tags]
    meta_library:
      author:
        avatar: https://cdn.jsdelivr.net/gh/SukiEva/HexoBlog/source/static/images/avatar.jpg
        name: SukiEva
        url: /
      # 文章创建日期
      date:
        icon: fa-duotone fa-calendar BELIZEHOLE
        title: '发布于：'
        format: 'll' # 日期格式 http://momentjs.com/docs/
      # 文章更新日期
      updated:
        icon: fa-duotone fa-calendar-pen ALIZARIN
        title: '更新于：'
        format: 'll' # 日期格式 http://momentjs.com/docs/
      # 文章分类
      category:
        icon: fa-duotone fa-folder-open SUNFLOWER
      # 文章浏览计数
      counter:
        icon: fa-duotone fa-eye
        unit: '次浏览'
      # 文章字数和阅读时长
      wordcount:
        icon_wordcount: fa-duotone fa-keyboard GREENSEA
        icon_duration: fa-duotone fa-hourglass ORANGE
      # 文章标签
      tags:
        icon: fa-duotone fa-tags GREENSEA

    # 文章页脚组件
    footer_widget:
      # ----------------
      # 参考资料、相关资料等 (for layout: post/docs)
      references:
        title: 参考资料
        icon: fa-duotone fa-quote-left fa-beat
        # 在 front-matter 中:
        #   references:
        #     - title: 某篇文章
        #       url: https://
        # 即可显示此组件。
      # ----------------
      # 版权声明组件 (for layout: post/docs)
      copyright:
        enable: true
        custom: false
        permalink: '<i class="fa-duotone fa-anchor"></i> 本文永久链接是：'
        content:
          - '<i class="fa-duotone fa-user PETERRIVE"></i> 本文由 [SukiEva](https://blog.sukiu.top) 创作，如果您觉得本文不错，请随意赞赏'
          - '<i class="fa-duotone fa-share-nodes TURQUOISE"></i> 博客内容遵循 [署名-非商业性使用-相同方式共享 4.0 国际 (CC BY-NC-SA 4.0) 协议](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh)'
          - permalink
          - '<i class="fa-duotone fa-circle-heart red"></i> 您的喜欢是作者写作最大的动力！'
      # ----------------
############################### Article Layout ############################### > end

############################### Comments ##################################### > start
comments:
  title: <i class='fa-solid fa-comments teal'></i> 评论
  service: giscus
  giscus:
    repo: SukiEva/HexoBlog
    repo-id: R_kgDONJxciw
    category: Announcements
    category-id: DIC_kwDONJxci84Cj8C7
    mapping: "title"
    reactions-enabled: "1"
    emit-metadata: "0"
    input-position: "top"
    lang: "zh-CN"
    loading: "lazy"
    theme:
      light: "light" # https://gcore.jsdelivr.net/gh/volantis-x/cdn-volantis@master/css/giscus/light.css
      dark: "dark" # https://gcore.jsdelivr.net/gh/volantis-x/cdn-volantis@master/css/giscus/dark.css
############################### Comments ##################################### > end

############################### Sidebar ###################################### > start
# 侧边栏
sidebar:
  position: left # left right
  # 主页、分类、归档等独立页面
  for_page: []
  # layout: docs/post 这类文章页面
  for_post: [toc, blogger]
  # 侧边栏组件库
  widget_library:
    # toc widget (valid only in articles)
    toc:
      class: toc
      display: [desktop, mobile] # [desktop, mobile]
      header:
        icon: fa-solid fa-list
        title: 本文目录
      list_number: true
      min_depth: 2
      max_depth: 5
    # blogger info widget
    blogger:
      class: blogger
      display: [desktop]
      avatar: https://cdn.jsdelivr.net/gh/SukiEva/HexoBlog/source/static/images/avatar.jpg
      shape: rectangle # circle, rectangle
      title: #SukiEva
      subtitle: #Developer
      jinrishici: '欲买桂花同载酒，终不似，少年游。' # Poetry Today. You can set a string, and it will be displayed when loading fails.
      url: /about/
      social:
        - icon: fas fa-compass
          url: https://sukiu.top
        - icon: fab fa-github
          url: https://github.com/SukiEva
        - icon: fa-solid fa-envelope
          url: Mailto:dev.suki@outlook.com
        - icon: fas fa-rss PUMPKIN
          url: /rss.xml
    # ---------------------------------------
    # category widget
    category:
      class: category
      display: [desktop] # [desktop, mobile]
      header:
        icon: fas fa-folder-open SUNFLOWER
        title: 文章分类
        url: /categories/
    # ---------------------------------------
    # tagcloud widget
    tagcloud:
      class: tagcloud
      display: [desktop] # [desktop, mobile]
      header:
        icon: fas fa-tags GREENSEA
        title: 热门标签
        url: /tags/
      min_font: 14
      max_font: 24
      color: true
      start_color: '#999'
      end_color: '#555'
    # ---------------------------------------
    # webinfo widget
    webinfo:
      class: webinfo
      display: [desktop, mobile]
      sticky: false
      header:
        icon: fa-solid fa-award PUMPKIN
        title: 站点信息
      type:
        article:
          enable: true
          text: '文章数目：'
          unit: '篇'
        runtime:
          enable: true
          data: '2021/09/19'    # 填写建站日期
          text: '已运行时间：'
          unit: '天'
        wordcount:
          enable: true
          text: '本站总字数：'   # 需要启用 wordcount
          unit: '字'
        visitcounter:
          siteuv:
            enable: true
            text: '本站访客数：'
            unit: '人'
          sitepv:
            enable: true
            text: '本站总访问量：'
            unit: '次'
        lastupd:
          enable: true
          friendlyShow: true    # 更友好的时间显示
          text: '最后活动时间：'
          unit: '日'
    # ---------------------------------------
    # lastupdate widget
    lastupdate:
      class: lastupdate
      display: [desktop]
      header:
        icon: fa-solid fa-clock WISTERIA
        title: 最近更新
    # ---------------------------------------
############################### Sidebar ###################################### > end

############################### Site Footer ################################## > start
site_footer:
  layout: [copyright, powerby]
  copyright: 'Copyright © Since 2021 <i class="fas fa-heartbeat animated faa-vertical" style="color:#f66"></i> SukiEva'
  powerby: >
    Modify from <a href="https://github.com/volantis-x/hexo-theme-volantis">Volantis</a> theme
    <i class="fa-duotone fa-bolt fa-bounce light-blue"></i>
    Powered by <a href="http://hexo.io/">Hexo</a>

############################### Site Footer ################################## > end

############################### Tag Plugins ################################## > start
# 内置标签插件的配置
tag_plugins:
  note: # style for default note:
    iconfont: 'Font Awesome 6 Pro'
############################### Tag Plugins ################################## > end

############################### Plugins ###################################### > start
plugins:
  fontawesome: https://cdn.jsdelivr.net/gh/inkss/fontawesome@6.0.0/css/all.min.css
  fontawesome_animation: # fontawesome animation for fontawesome V5
    enable: true
  darkmode: # 暗黑模式
    enable: true
  wordcount: # npm i hexo-wordcount
    enable: true
  preload: # 预加载
    enable: true
  lazyload: # 图片懒加载
    enable: true
  scrollreveal: # https://scrollrevealjs.org/api/reveal.html
    enable: true
  nodewaves: # Button Ripple Effect
    enable: true
  comment_typing: # Typing Effects
    enable: true
  killOldVersionsOfIE: # 旧版 Internet Explorer 淘汰行动
    enable: true
  killNoScript: # 禁用JavaScript提示
    enable: true
  swiper: # https://www.swiper.com.cn/
    enable: true
  message: # 音乐通知，播放、暂停、失败 时的图标
    enable: true
    copyright:  # 是否在复制时弹出版权提示
      enable: true
    aplayer:
      enable: false
############################### Plugins ###################################### > end

############################### Rightmenu #################################### > start
rightmenus:
  enable: true
  order:
    - plugins.navigation
    - hr
    - plugins.inputBox
    - plugins.seletctText
    - plugins.elementCheck
    - plugins.elementImage
    - hr
    - menus.prevNext
    - hr
    - menus.links
    - hr
    - menus.darkMode
    - hr
    - plugins.articlePage
    - hr
  options:
    # 图标前缀 fa-solid, fa-regular, fa-light, fa-thin, fa-duotone, fa-brands
    iconPrefix: fa-duotone PETERRIVE
    # 例外，在 articlePage 组显示时（文章页）时依旧显示含 link 属性的菜单项
    articleShowLink: false
    # 当设定全局音乐播放器时，是否一直显示音乐控制菜单。false：仅当音乐播放时启用
    musicAlwaysShow: true
  plugins:
    # 导航组件
    navigation:
      - {id: 'left', name: '转到上一页', icon: 'fa-duotone fa-arrow-left PETERRIVE', event: 'history.back()', group: 'navigation'}
      - {id: 'right', name: '转到下一页', icon: 'fa-duotone fa-arrow-right PETERRIVE', event: 'history.forward()', group: 'navigation'}
      - {id: 'redo', name: '刷新当前页面', icon: 'fa-duotone fa-redo PETERRIVE', event: 'window.location.reload()', group: 'navigation'}
      - {id: 'up', name: '回到顶部', icon: 'fa-duotone fa-arrow-up PETERRIVE', event: 'VolantisApp.scrolltoElement(volantis.dom.bodyAnchor)', group: 'navigation'}
    # 文章页面组件
    articlePage:
      - {id: 'home', name: '回到首页', icon: 'fa-duotone fa-home PETERRIVE', link: '/', group: 'articlePage'}
      - {id: 'printMode', name: '打印页面', icon: 'fa-duotone fa-print TURQUOISE', event: 'printMode', group: 'articlePage'}
      - {id: 'readMode', name: '阅读模式', icon: 'fa-duotone fa-book-open EMERALD', event: 'readMode', group: 'articlePage'}
    # 文本输入框相关组件
    inputBox:
      - {id: 'copyPaste', name: '粘贴文本', icon: 'fa-duotone PETERRIVE fa-paste', event: 'copyPaste', group: 'inputBox'}
      - {id: 'copyAll', name: '全选文本', icon: 'fa-duotone PETERRIVE fa-object-ungroup', event: 'copyAll', group: 'inputBox'}
      - {id: 'copyCut', name: '剪切文本', icon: 'fa-duotone PETERRIVE fa-cut', event: 'copyCut', group: 'inputBox'}
    # 文本选中类组件
    seletctText:
      - {id: 'copyText', name: '复制文本', icon: 'fa-duotone PETERRIVE fa-copy', event: 'copyText', group: 'seletctText'}
      - {id: 'searchWord', name: '站内搜索', icon: 'fa-duotone PETERRIVE fa-search', event: 'OpenSearch(__text__)', group: 'seletctText'}
      - {id: 'bingSearch', name: '谷歌搜索', icon: 'fa-duotone PETERRIVE fa-search', event: 'window.open(`https://google.com/search?q=${__text__}`)', group: 'seletctText'}
    # 链接判断组件
    elementCheck:
      - {id: 'openTab', name: '新标签页打开', icon: 'fa-duotone PETERRIVE fa-external-link-square-alt', event: 'window.open(__link__)', group: 'elementCheck'}
      - {id: 'copyLink', name: '复制链接地址', icon: 'fa-duotone PETERRIVE fa-link', event: 'copyLink', group: 'elementCheck'}
    # 图片判断类组件
    elementImage:
      - {id: 'copyImg', name: '复制图片', icon: 'fa-duotone PETERRIVE fa-image', event: 'copyImg', group: 'elementImage'}
      - {id: 'googleImg', name: '谷歌识图', icon: 'fa-duotone PETERRIVE fa-images', event: 'window.open(`https://www.google.com/searchbyimage?image_url=${__link__}`)', group: 'elementImage'}
  menus:
      darkMode:
        - {id: 'darkMode', name: '夜间模式', icon: 'fa-duotone fa-eclipse-alt WISTERIA', event: 'volantis.dark.toggle()', group: 'darkMode'}
############################### Rightmenu #################################### > end

############################### Custom css ################################### > start
custom_css:
  cursor:
    enable: false
  font_smoothing: true #抗锯齿
  navbar:
    width: auto # auto, max
    effect: [] # [shadow, floatable, blur]
  sidebar:
    effect: [] # [shadow, floatable, blur]
  body:
    effect: [] # [shadow, floatable, blur]
  fontfamily:
    logofont:
      fontfamily: 'JetBrains Mono'
      name: 'JetBrains Mono'
      url: https://cdn.jsdelivr.net/gh/JetBrains/JetBrainsMono/ttf/JetBrainsMono-Regular.ttf
    bodyfont:
      fontfamily: 'HarmonySansSC'
      name: 'HarmonySansSC'
      url: https://cdn.jsdelivr.net/gh/SukiEva/HexoBlog/source/static/fonts/HarmonySansSC.ttf
    codefont:
      fontfamily: 'JetBrains Mono'
      name: 'JetBrains Mono'
      url: https://cdn.jsdelivr.net/gh/JetBrains/JetBrainsMono/ttf/JetBrainsMono-Regular.ttf
############################### Custom css ################################### > end

############################### Color Scheme ################################# > start
color_scheme:
  # ------------
  # 通用颜色
  common:
    # 主题色
    theme: '#44D7B6'
    # 链接色
    link: '#2196f3'
    # 按钮色
    button: '#44D7B6'
    # 鼠标放到交互元素上时的色
    hover: '#ff5722'
    # 主题色块内部的文字颜色
    inner: '#fff'
    # 选中区域文字的背景颜色
    selection: 'alpha(#2196f3, 0.2)'
  # ------------
  # 亮色主题（默认）
  light:
    # 网站背景色
    site_bg: '#fff'
    # 卡片背景色
    card: '#fff'
    codeblock: '#f6f6f6'
  # ------------
  # 暗色主题
  dark:
    site_bg: '#000'
    card: '#121212'
    block: '#1f1f1f'
    codeblock: '#1f1f1f'
    inlinecode: '#ff003c'
############################### Color Scheme ################################# > end

############################################################################## > start
# 全局页面字符串替换  A => B (可用于临时修改错字等)
# replace:
#  - https://cdn.jsdelivr.net/npm/ => https://unpkg.com/
  # - https://cdn.jsdelivr.net/gh/ => https://fastly.jsdelivr.net/gh/
  # - https://unpkg.com/ => https://fastly.jsdelivr.net/npm/
cdn:
  enable: true
# 统计
analytics:
  leancloud:
    app_id: 60Pgr6NOujhBha2UCa8PId6g-MdYXbMMI
    app_key: vkpRJpKQC8VIG9YnYzC9toy2

custom_files:
  first: source/_volantis/style/first.styl
  style: source/_volantis/style/style.styl
  dark: source/_volantis/style/dark.styl
  darkVar: source/_volantis/style/darkVar.styl
  headBegin: source/_volantis/inject/headBegin.ejs
  headEnd: source/_volantis/inject/headEnd.ejs
  header: source/_volantis/inject/header.ejs
  topMeta: source/_volantis/inject/topMeta.ejs
  bottomMeta: source/_volantis/inject/bottomMeta.ejs
  postEnd: source/_volantis/inject/postEnd.ejs
  bodyBegin: source/_volantis/inject/bodyBegin.ejs
  bodyEnd: source/_volantis/inject/bodyEnd.ejs
############################################################################## > end